### ISSUE TITLE
udaje o cestovnych poriadkoch verejnej dopravy

### ISSUE THREAD

**Issue by hanecak** [OpenDataSk/SK-Dataset-WishList#9]
Vo verejnej konzultacii v roku 2015, ktoru organizoval USV ROS, boli ako prioritne vyhodnotene udaje o cestovnych poriadkoch verejnej dopravy:

> Cestovné poriadky (Ministerstvo dopravy, výstavby a regionálneho rozvoja). Záujem je o diaľkovú, prímestskú aj mestskú hromadnú dopravu (dáta sú dôležité na vypočítanie reálnej dostupnosti zaostalých regiónov), autobusy aj vlaky všetkých registrovaných prepravcov, vrátane súkromných. Na zverejnenie by sa mal použiť štandardný formát, napr. GTFS. Cestovné poriadky schvaľujú dopravné úrady, pre ich nahranie existuje CIS CP. Dáta ale nie sú verejne dostupné. O CIS CP pred niekoľkými rokmi písal Bus portál. Pre budúcnosť by bolo dobré uvažovať o sprístupnení dát z palubných počítačov (napr. poloha dopravného prostriedku MHD v reálnom čase). Tieto sa môžu využiť pre optimalizáciu trás, ale aj užitočnejšie mobilné aplikácie.

Referencia: https://github.com/otvorenavlada/akcnyplan2015/tree/master/uloha-03

**Comment by hanecak** [comment]
18.01.2018 bolo v ŽSR, Železničné telekomunikácie, Kováčska 3, Bratislava stretnutie medzi ŽSR a USV ROS ohladom aj tohto a:

* exkluzivna zmluva ktora branila poskytnutiu dat v minulosti bola osetrena, dnes uz zverejneniu nebrani
* k udajom existuje "interne API"
* dalsi plan je, ze NASES cez to interne API" udaje ziska od ZSR a nasledne poskytne ako Open Data cez data.gov.sk
  * tot plnenie uloh B.9 a B.15 Uznesenia vlády SR č. 04/2017 k Akčnému plánu Iniciatívy pre otvorené vládnutie v SR na roky 2017-2019
* sucastou udajov je aj zoznam zeleznicnych stranic, ku ktoremu vie ZSR (opat pre NASES,alebo USV ROS) poskytnut export s par detailami navyse (z ineho systemu)

**Comment by hanecak** [comment]
Na zaklade stretnuti medzi USV ROS a ZSR budu vyzera v blizkom case zrejme zverejnene niektore udaje. Referencie:

- https://platforma.slovensko.digital/t/ake-data-otvorit-na-zelezniciach/2484/92
- https://platforma.slovensko.digital/t/ake-data-otvorit-na-zelezniciach/2484/94

Ak sa tak stane, tak:

1. z pohladu celostanej zeleznicnej dopravy mozeme tento dopyt povazovat za vyrieseny, ale
2. z pohladu ostanej dopravy vsak stale za nevyrieseny.

Formalne teda asi vytvorim "sub-issues", aby bolo jasne ze "ZSR splnilo" ale "caka sa na ostanych".

**Comment by Zippersk** [comment]
Nejaký update po vyše pol roku?  Vidím na ich stránke nejaké API na vyhľadanie staníc (ktoré je asi neverejné, ale chýba im tam `allow-origins` header) - https://www.slovakrail.sk/services/FindStations?term=dolny

**Comment by hanecak** [comment]
Update bol, k nemu tiez oneskoreny update:

* ZSR sprevadzkovali zverejnovanie v spolupraci s o.i. studentmi PriF UK, podla data.gov.sk zhruba k februaru 2019
* zaznam datasetu: https://data.gov.sk/dataset/https-www-zsr-sk-files-pre-cestujucich-cestovny-poriadok-gtfs-gtfs-zip
* udaje vo forme GTFS: https://data.gov.sk/dataset/https-www-zsr-sk-files-pre-cestujucich-cestovny-poriadok-gtfs-gtfs-zip/resource/b63c856d-bae1-459e-831a-f0a93979c76e
* licencia CC0

Povazujem teda za vyriesene.

**Comment by Martinedo** [comment]
čiže vlastne tie data sú už neaktuálne. Plánuje sa aj nový dataset, napr. 2021? či to bolo len pre potreby nejakej diplomovky vtedy?

**Comment by hanecak** [comment]
Nuz, k dnesku (24.3.2021) linka na samotne data vracia "zero sized reply" ( https://www.zsr.sk/files/pre-cestujucich/cestovny-poriadok/gtfs/gtfs.zip ). Principilane teda zverejnuju (t.j. tento issue nadalej povazujem za vyrieseny), ale teda zlyhala prevadzka, t.j. ze chybali aktuallizacie resp. teraz vobec nefunguje.

Na to tu issue tracker (ako komunita) nemame a neviem ani o issue tracker pre ZSR. Ale teda posunul som informaciu o nefuncknosti a neaktualnosti na MIRRI. Hadam pomoze.

Edit (k 26.3.2021): Kedze teda nemame "prevadzkovy issue tracker" (ani my, ani stat), tak aspon sem: MIRRI moj mail posunulo na MinDop. Odpoved som dostal vcera. Vyzera, ze som trafil nejake maintenance okno. Data sa uz teraz stiahnut opat daju a vyzeraju OK.
